CREATE TABLE Insurance (
  InsurerID BIGINT PRIMARY KEY,
  CompanyName VARCHAR(255) NOT NULL
);

CREATE TABLE Patient (
  PatientID BIGINT PRIMARY KEY,
  PatientName VARCHAR(255) NOT NULL,
  ZipCode INT NOT NULL,
  IID BIGINT REFERENCES Insurance,
  InsurancePolicy VARCHAR
);

CREATE TABLE Clinic (
  ClinicID BIGINT PRIMARY KEY,
  ClinicName VARCHAR(255) NOT NULL,
  Address VARCHAR(255) NOT NULL
);

CREATE TABLE Visits (
  VisitID BIGINT PRIMARY KEY,
  PID BIGINT REFERENCES Patient NOT NULL,
  CID BIGINT REFERENCES Clinic NOT NULL,
  Reason VARCHAR(255) NOT NULL,
  VisitTime DATE NOT NULL,
  Cost MONEY NOT NULL,
  Debt MONEY NOT NULL
);

CREATE TABLE AcceptedBy (
  IID BIGINT REFERENCES Insurance,
  CID BIGINT REFERENCES Clinic,
  PRIMARY KEY (IID, CID)
);
